"use client";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";

type Job={id:string;source:string;company:string;title:string;location:string;workplaceType:string;employmentType:string;description:string;postedAt:string;applyUrl:string;jobUrl:string};
export default function JobsPage(){
 const router=useRouter(); const [q,setQ]=useState(""); const [loc,setLoc]=useState(""); const [jobs,setJobs]=useState<Job[]>([]);
 const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [page,setPage]=useState(0); const [pages,setPages]=useState(1); const [total,setTotal]=useState(0); const [saved,setSaved]=useState<string[]>([]);
 useEffect(()=>{let initial="";try{const p=JSON.parse(localStorage.getItem("vroom-user-profile")||"{}");initial=p.targetRole||"";setQ(initial);setSaved(JSON.parse(localStorage.getItem("vroom-saved-jobs")||"[]"))}catch{}load(0,initial,"")},[]);
 async function load(pg=0,query=q,location=loc){setLoading(true);setError("");try{const s=new URLSearchParams({page:String(pg)});if(query.trim())s.set("query",query.trim());if(location.trim())s.set("location",location.trim());const r=await fetch(`/api/jobs?${s}`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not load jobs");setJobs(d.jobs||[]);setPage(d.page||0);setPages(d.pageCount||1);setTotal(d.total||0)}catch(e){setError(e instanceof Error?e.message:"Could not load jobs");setJobs([])}finally{setLoading(false)}}
 function search(e:FormEvent){e.preventDefault();load(0,q,loc)}
 function save(j:Job){const ids=saved.includes(j.id)?saved.filter(x=>x!==j.id):[...saved,j.id];setSaved(ids);localStorage.setItem("vroom-saved-jobs",JSON.stringify(ids));localStorage.setItem(`vroom-job:${j.id}`,JSON.stringify(j))}
 function details(j:Job){localStorage.setItem(`vroom-job:${j.id}`,JSON.stringify(j));router.push(`/jobs/${encodeURIComponent(j.id)}`)}
 return <main className="min-h-screen bg-[#080b16] text-white">
 <header className="border-b border-white/[.07]"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 sm:px-8"><button onClick={()=>router.push("/dashboard")} className="rounded-xl border border-white/10 px-3 py-2 text-sm text-slate-300">← Dashboard</button><div className="text-right"><h1 className="font-bold">VRoom AI Jobs</h1><p className="text-[10px] uppercase tracking-[.18em] text-slate-500">Company openings · Direct application</p></div></div></header>
 <div className="mx-auto max-w-7xl px-5 py-8 sm:px-8">
 <section className="rounded-3xl border border-emerald-400/15 bg-gradient-to-br from-emerald-500/15 via-cyan-500/5 to-transparent p-6 sm:p-8"><span className="text-xs font-semibold uppercase tracking-[.18em] text-emerald-300">Direct company jobs</span><h2 className="mt-2 text-3xl font-bold">Find. Prepare. Apply.</h2><p className="mt-2 text-sm text-slate-400">Job details stay inside VRoom AI. Apply Now opens the employer's active ATS application form.</p>
 <form onSubmit={search} className="mt-6 grid gap-3 md:grid-cols-[1fr_1fr_auto]"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Role — AI Engineer" className="rounded-xl border border-white/10 bg-[#0b0f1d] px-4 py-3 text-sm outline-none"/><input value={loc} onChange={e=>setLoc(e.target.value)} placeholder="Location — India / Remote" className="rounded-xl border border-white/10 bg-[#0b0f1d] px-4 py-3 text-sm outline-none"/><button className="rounded-xl bg-emerald-400 px-6 py-3 text-sm font-bold text-[#07110d]">Search</button></form></section>
 <div className="mb-5 mt-8 flex justify-between"><div><h3 className="text-xl font-bold">{q?`Jobs for "${q}"`:"Current openings"}</h3><p className="mt-1 text-xs text-slate-500">{total} matching openings</p></div></div>
 {error&&<div className="mb-4 rounded-xl border border-red-400/20 bg-red-500/10 p-4 text-sm text-red-300">{error}</div>}
 {loading?<div className="flex min-h-72 items-center justify-center"><div className="h-10 w-10 animate-spin rounded-full border-2 border-emerald-400 border-t-transparent"/></div>:jobs.length===0?<div className="rounded-2xl border border-white/10 p-10 text-center text-slate-400">No matching jobs found. Try a broader role or clear the location.</div>:<div className="grid gap-4 lg:grid-cols-2">{jobs.map(j=><article key={j.id} className="rounded-2xl border border-white/[.08] bg-white/[.025] p-5"><div className="flex items-start justify-between gap-4"><div><h4 className="text-lg font-semibold">{j.title}</h4><p className="mt-1 text-sm text-emerald-300">{j.company}</p><p className="mt-1 text-xs text-slate-500">{j.location||"Location not listed"} {j.workplaceType?`· ${j.workplaceType}`:""}</p></div><span className="rounded-full border border-white/10 px-2.5 py-1 text-[10px] uppercase text-slate-500">{j.source}</span></div><p className="mt-4 line-clamp-3 text-sm leading-6 text-slate-400">{j.description}</p><div className="mt-5 flex flex-wrap gap-2"><button onClick={()=>details(j)} className="rounded-xl bg-white px-4 py-2.5 text-xs font-semibold text-[#101426]">View Details</button><a href={j.applyUrl} target="_blank" rel="noreferrer" className="rounded-xl bg-emerald-400 px-4 py-2.5 text-xs font-bold text-[#07110d]">Apply Now ↗</a><button onClick={()=>save(j)} className="rounded-xl border border-white/10 px-4 py-2.5 text-xs text-slate-300">{saved.includes(j.id)?"★ Saved":"☆ Save"}</button></div></article>)}</div>}
 <div className="mt-8 flex justify-center gap-3"><button disabled={page<=0||loading} onClick={()=>load(page-1)} className="rounded-xl border border-white/10 px-4 py-2 text-xs disabled:opacity-30">Previous</button><span className="py-2 text-xs text-slate-500">Page {page+1}/{pages}</span><button disabled={page+1>=pages||loading} onClick={()=>load(page+1)} className="rounded-xl border border-white/10 px-4 py-2 text-xs disabled:opacity-30">Next</button></div>
 </div></main>
}